### ISSUE TITLE
Feature Request: GPT Vision 

### ISSUE THREAD

**Issue by ipod86** [ToGe3688/ioBroker.ai-toolbox#10]
The name AI Tools implies that there should be a collection for different AI applications. 

I think it would be practical to be able to use GPT Vision via the adapter. 
For example, different vision bots in which you can define different questions that are triggered when a DP with an image path changes. 

I built something like that here with Blockly and a JS function.
[https://forum.iobroker.net/topic/78608/bilder-mittels-llm-chatgpt-vision-ananalysieren](https://forum.iobroker.net/topic/78608/bilder-mittels-llm-chatgpt-vision-ananalysieren)

**Comment by ToGe3688** [comment]
Good call! I checked all the APIs and included vision capabilities in the new release. As i currently dont have an OpenAI API account it would be nice if you could check if it works as expected. I tried with Anthropic and OpenRouter, seems to be working fine so far!

**Comment by ipod86** [comment]
Do I have to fill in the image_url first and then the text request? I can't get a response from the bot. I could provide my key (private) for testing.

**Comment by ipod86** [comment]
![Screenshot_20241226_224111_Chrome](https://github.com/user-attachments/assets/bbadc3d9-c460-4bec-bf08-92c842ff0bcb)

**Comment by ToGe3688** [comment]
Klar, Deutsch geht natürlich auch! Wie groß war denn das Bild welches du versucht hast abzusenden? Vom Ablauf her erst den image_url Datenpunkt setzen und dann text_request, dann wird das Bild mit dem Text mit übermittelt.

**Comment by ipod86** [comment]
Es war dieses Bild:

[https://herzanhirn.de/wp-content/uploads/2020/01/unteres-schloss-siegen-sehenswuerdigkeiten-ausflug-13.jpg

Bekommt grad am Smartphone die Auflösung nicht raus.

Ich fände es auch sehr praktisch, lokale Bildpfade angeben zu können (wie in meinem Script).
Ich zB hab einen kleinen Telegram Chatbot gebaut. Dort wird der Bildpfad aus Telegram genommen von den Bildern die ich in den Telegrambot sende.

**Comment by ToGe3688** [comment]
Das Bild macht bei mir mit OpenRouter und Gpt-4o-mini keine Probleme. Mit den lokalen Dateipfaden ist noch eine gute Ergänzung, werde ich mit aufnehmen. Da ja sowieso in Base64 umgewandelt werden muss sollte es da keine Probleme geben.

**Comment by ipod86** [comment]
Hab es grad nochmal getestet und bin von 4o auch mal auf 4p mini gegangen. Die Fehlermeldung bleibt aber gleich.

Das wäre praktisch.

**Comment by ToGe3688** [comment]
Die Fehlermeldung kann ich noch nicht nachvollziehen, ich habe aber mal auf Basis deiner Vorlage die Möglichkeit ergänzt lokale Dateien zu verwenden. Nach dem Update einfach den Pfad in .image_url einfügen und dann den text_request starten.

**Comment by ipod86** [comment]
Lokales Bild klappt 👍
