### ISSUE TITLE
Gpt models do not work

### ISSUE THREAD

**Issue by ipod86** [ToGe3688/ioBroker.ai-toolbox#9]
None of the GPT models work for me. A token is stored. This also works in another script of mine.

ai-toolbox.0.Models.gpt-4o.request.body
`{"model":"gpt-4o","max_tokens":2000,"temperature":0.6,"messages":[{"role":"user","content":"Geht's dir gut? "}]}
`
ai-toolbox.0.Models.gpt-4o.request.state
`error`

ai-toolbox.0.Models.gpt-4o.response.error
`Cannot read properties of undefined (reading 'bot_name')`

ai-toolbox.0.Models.gpt-4o.response.raw
`{}`

However, if I go over ai-toolbox.0.Models.meta-llamallama-32-3b-instructfree.text_request everything works.

Adapter Version 0.0.2

**Comment by kopierschnitte** [comment]
Perhaps try to define and use a preset (aka "bot"). I'm quite sure that direct commands to a models don't work at the moment.

**Comment by ipod86** [comment]
I have exactly the same error. Only with the data points within the bot. 
![Screenshot_20241225_092844_Chrome](https://github.com/user-attachments/assets/644ce994-b411-4362-896a-7cab35e79f21)

![Screenshot_20241225_092950_Chrome](https://github.com/user-attachments/assets/3d8f2666-756a-4e6a-aa79-319e84b7b738)

**Comment by kopierschnitte** [comment]
Strange. I've tried it the same (but using LocalAI instead of OpenAI) and it worked perfectly.
Maybe the dev can help :-(

**Comment by kopierschnitte** [comment]
There's a new release which looks promising!

**Comment by ToGe3688** [comment]
Thank you for reporting the problem. There was a bug with the OpenAI Api provider, i fixed this and created a new release. Could you please install again from Github. Should work now! If it does not work please switch the adapter to debug logging and attach the log when you make a request.

**Comment by ipod86** [comment]
It works in the new release. 

Thank you very much.
